# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
#This container uses macvlan network. Please make sure your macvlan network is created and name local-network. Change "local-network" below if named differently.
---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    hostname: pihole               #Hostname
    networks:
       pihole-network:
          ipv4_address: 10.0.0.50  #Change, to your pihole address in your subnet
    environment:
       TZ: 'America/Chicago'
       WEBPASSWORD: '12345678'
    # Volumes store your data between container upgrades
    volumes:
      - 'CHANGE_TO_COMPOSE_DATA_PATH/pihole/etc-pihole:/etc/pihole'
      - 'CHANGE_TO_COMPOSE_DATA_PATH/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#    cap_add:
#      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
networks:
  pihole-network:
     name: local-network
     external: true
