---
services:
    adguardhome:
        container_name: adguardhome
        image: adguard/adguardhome
        networks:
          adguardhome:
            ipv4_address: 192.168.178.203  #Change this to your ip address
        volumes:
            - CHANGE_TO_COMPOSE_DATA_PATH/adguardhome/workdir:/opt/adguardhome/work
            - CHANGE_TO_COMPOSE_DATA_PATH/adguardhome/confdir:/opt/adguardhome/conf
        restart: unless-stopped
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 67:67/udp
            - 68:68/udp
            - 80:80/tcp
            - 443:443/tcp
            - 443:443/udp
            - 3000:3000/tcp #Admin interface
            - 853:853/tcp
            - 784:784/udp
            - 853:853/udp
            - 8853:8853/udp
            - 5443:5443/tcp
            - 5443:5443/udp
        labels:
            -homepage.group=Netzwerk
            -homepage.icon=adguard-home.svg
            -homepage.href=https://adguard.domain.tld/ #change domain
            -homepage.description=DNS Server
            -homepage.server=server1-docker
            -homepage.container=adguardhome
            #-sitemonitor: https://adguard.domain.tld/ #change domain
            -homepage.widget.type=adguard
            -homepage.widget.url=https://adguard.domain.tld/ #change domain
            -homepage.widget.username={{HOMEPAGE_VAR_ADGUARD_USERNAME}} #.env file
            -homepage.widget.password={{HOMEPAGE_VAR_ADGUARD_PASSWORD}} #.env file

networks:
   adguardhome:
      name: local_network  #This is the name of our macvlan
      external: true
