---
services:
   vaultwarden:
      container_name: vaultwarden
      image: vaultwarden/server:latest
      volumes:
         - CHANGE_TO_COMPOSE_DATA_PATH/vaultwarden/vw-data/:/data/
      networks:
         vaultwardennet:
      ports:
         - 8081:80
      restart: unless-stopped
      environment:
         - ADMIN_TOKEN=$password$password$password$password$password # Change this Token
networks:
  vaultwardennet:
    name: proxy_network
    external: true
