services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    networks:
          duplicati:
            ipv4_address: 192.168.178.206  #Change this to your ip address
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      - SETTINGS_ENCRYPTION_KEY=changeme #change minimum 8 characters, alphanumeric
      - CLI_ARGS= #optional
      - DUPLICATI__WEBSERVICE_PASSWORD= #optional
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/duplicati/config:/config
      #- /path/to/backups:/backups
      - CHANGE_TO_COMPOSE_DATA_PATH:/source/docker_compose
    ports:
      - 8200:8200
    restart: unless-stopped
networks:
   duplicati:
      name: local_network  #This is the name of our macvlan
      external: true
